server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users-ws
          predicates:
            - Path=/users/**
        - id: account-management-service
          uri: lb://account-ws
          predicates:
            - Path=/account/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}