server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest