server:
  port: 0
spring:
  application:
    name: accounts-ws
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
