server:
  port: ${PORT:0}
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users-ws
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest